services:
  - type: web
    name: bookmyshow
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: 'python manage.py migrate && echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(\"admin\", \"admin@example.com\", \"Admin@123\")" | python manage.py shell && sleep 10 && gunicorn bookmyshow.wsgi:application'
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
