services:
  - type: web
    name: bookmyshow
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn bookmyshow.wsgi:application"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
